version: 1.0.{build}
branches:
  only:
  - master
only_commits:
  files:
    - src/
image: Visual Studio 2017
before_build:
- cmd: nuget restore src\Msfx.DI.sln
build:
  verbosity: minimal
