# This is a basic workflow to help you get started with Actions

name: Lab

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, ${{ github.actor }}!
      
    - name: Echo current date
      id: generate_version
      run: echo "::set-output name=version::v-$(Get-Date -format 'yy.MM.dd')"
      
    - name: Echo version
      run: echo version=${{ steps.generate_version.outputs.version }}
      


