# This is a basic workflow to help you get started with Actions

name: Msfx CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout the code  
      uses: actions/checkout@v2
      
    # Setting the MSBuild path 
    - name: Setup the MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.1

    # Setting the Nuget
    - name: Setup the NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
      
    # Restore Nuget packages
    - name: Restore Nuget packages
      run: nuget restore src\Msfx.DI.sln

    # Build and Publish artifacts locally
    - name: Build and Publish
      run: msbuild src\Msfx.DI.sln /p:Configuration=Release
      
    # Add Release to Github
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MSFX_DI_CI_TOKEN }}
